server:
  port: 9090
  servlet:
    encoding:
      force-response: true


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project
    username : root
    password : 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 903684776912-1mjksa1mapb1i2dncofmnnd4khf8ln7i.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:9090/login/oauth2/code/google"
            scope: profile,email
          kakao:
            authorization-grant-type: authorization_code
            client-id: 5d832b131cb4d7f7542583266310cf28
            client_secret: M9PWuTnBtvRP00P9IQbnej08iKWjCH3P
            redirect-uri: "http://localhost:9090/auth/kakao/callback"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            client-authentication-method: POST
          naver:
            authorization-grant-type: authorization_code
            client-id : nCDCdfuNdc_YHODg03yu
            client-secret : l7RBmMuSIO
            redirect-uri: "http://localhost:9090/login/oauth2/code/naver"
            scope: name, nickname, email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging:
  level:
    org:
      springframework: debug

